DATABASE_URL: ENC[AES256_GCM,data:BSIxTJCBESAhpMbzaVqYfm1SSd2Y9QrYPO3ZfAQiiKRyTiCqRGcuepmgp/V54eGEV4cgYFJ37609,iv:8oTXUF2VlywMDyRhJx1z7+ywpI679R3hwcEufrVTJHg=,tag:Ve4Ho8eNtTQ/slvhtSp8Lw==,type:str]
NEO4J_URI: ENC[AES256_GCM,data:uFjWybUtuwdI8gREmCbMac5u6fem,iv:JJLoZ5Ue0DDCvXwHI4NSxv7izLmCVYJAayuzFygpEIM=,tag:lY9l7VoGKJNONqWrtk98UA==,type:str]
NEO4J_USER: ENC[AES256_GCM,data:s0R3yUE=,iv:asBJ6Fp5LE5L45NVibhjMkErC0RAKvwHfndLQ3tis5w=,tag:zwLlP0yQjVofkKqX6NtIiA==,type:str]
NEO4J_PASSWORD: ENC[AES256_GCM,data:wU76b0H37A1H,iv:FQSvRtkF3w2p2scL6y3TXHohX8dqz1G50mqmPiPyCLA=,tag:KIjsEjAs9eBWHMLYdK2ubw==,type:str]
REDIS_URL: ENC[AES256_GCM,data:JZn91z2Jy5QafGtND+hmY1CsvnUekHqI,iv:W3SDk0LyqQPjTd9DvtYrfwNG0lOIHj3Cvwd/w7pan1o=,tag:DmeNvitSwBfGDK+DzvPV8g==,type:str]
JWT_SECRET: ENC[AES256_GCM,data:sbhexhDfP3X7foqSrIk5YBfiEWncax/epK5qMZBsDOn72pqzR9+VLM+AJYj6,iv:kzwFw9lLO/xJReZnCkJFWM0nlbfSGFFRtsgKcOoIQC4=,tag:Hd7CipXp6I2YJdeGmCf8EA==,type:str]
ENV: ENC[AES256_GCM,data:FPiNMTIpGhGfQxI=,iv:8VuQdYtiaFwUxcfl03pI2BBdBQLKtKs1m81WqblPC68=,tag:n0MUaqeNsuqOaowo8AUi/w==,type:str]
CORS_ORIGINS: ENC[AES256_GCM,data:cpASJhY99mByV/sV2IHzxlMqTBzyeMyh2u83K8jnHCYjsvKwT2+oCWzIbQ==,iv:pMNxaca+vN5cI/TiARpn2/u/7i/kPL/33e92Qxin8EM=,tag:8moSBEmGfftH7SnH7I1NFw==,type:str]
WS_ORIGINS: ENC[AES256_GCM,data:TaPcbCPken7JcRvfRDPShYxS/NWN,iv:W8OOmyp2DptRyCwxNuSiqP1v/cA1fl3U2/D+Ff30qtY=,tag:yEi+WIZM9vvhYgeScMRYlw==,type:str]
sops:
    age:
        - recipient: age1uf70wtw4wad0l7yj39pjzcgzrlh2zg62560zmcq07dk3eg8g49fqkz8rl4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdVJYcUNpVVQ1dDE4cm1O
            eXF2b1d0bVFEZ1RyNzhlM0pNUjRzVmRqUVI0CmQyR3B6eUszNWNGZ1lMYzlGNDBz
            RzVvVXVLWmtDcmpHeFhpQXNoNDFKVWMKLS0tIE5GTXRNYjdkK0p2QXYwWHlXSHZI
            SkVnaFNaVGE4eWZKRWwxS2JqOUt5VjAKnjVlDktjXvUdQj8vN1iPmRuiY4nwMPx7
            kazF9y0xfmyP2yBZK72QoISdju6CYSWJCfR8omFzkmGynW/RI3Hu/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T22:58:43Z"
    mac: ENC[AES256_GCM,data:uk1/KdWcLhzDEeX+uSTtgjVLmOjHiQGIzFqK6LmTMYYZG8mzgNFd7b9wCJ+gUSYCAnTKAYVClT5gxFLvC08w4H5QzvLCbFDeaBXs0C1huyTjFnFvfTRKw1zkWAi6LPkuyu2CBjE7tmLbHOgmmjNABDpsV9/F8AtpgiInpWQR7S0=,iv:AFyItOY6yStgpXxy7UGCsXE1Uac84haUahEHQVw4VvE=,tag:JbTL/AwXJwEEFfnPFsLoJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
