DATABASE_URL: ENC[AES256_GCM,data:+zjYQ9vB+2QXP/xHln8oy7t7Qf4cd//iknKGcrdlppAyGmgPZnti/N56vfjTKYmNPqFfCBVZRxEx,iv:qEttys5SssT6ZLlvpu15VNaWzYng96LFbfr3xQIdT+w=,tag:mjOthVet1kG41lFB7vfLkw==,type:str]
REDIS_URL: ENC[AES256_GCM,data:xy8Bh2gsTe/yLzoBAOKWg5hFlIdxyuWC,iv:dmTiZsrr/6NlsABc853p/oo6atJ77+cwhrY0VnA2zT4=,tag:1Z/1QZaed0luC2gCYUJFBA==,type:str]
JWT_SECRET: ENC[AES256_GCM,data:GYubWRtZmiiIxcFSjoVa3OWMRZkM0o8C58Zg3zczohs44QNrf7cioHU5DGZ7,iv:DMiACW/tlBkZnooIQK9B+4g/Zz6XgO8NI6LK/P5vn+c=,tag:qzaKgCVSp2OwPYg2oFBWvA==,type:str]
ENV: ENC[AES256_GCM,data:PGxDrh94jfze+zE=,iv:KJsn1mjZKxB4v5l3UNfGO/otf9pzRuYbKL0FJG4ObIY=,tag:E47m6szoIYW8/8YIvd4RYg==,type:str]
CORS_ORIGINS: ENC[AES256_GCM,data:xGVvVvV1Ln5F01mKF0RznDB/3FYVrgXPoM8ZHKQF0r59ccJ6evYAFLfnOg==,iv:dHJZ73SRnAzEEO2Je2WYPItbtkZedkGd0qCPfQ6QWRs=,tag:kEH1BX5gyngKso0CzNVENA==,type:str]
WS_ORIGINS: ENC[AES256_GCM,data:tzfcxv/RRmhhjHXHR8m53W+vA7Iv,iv:vh02O8cQ780f61PRv60P+2HExgT5wRVYDsIyFHLDKAc=,tag:HVMofsZW7Y4x7KHf7N2mcg==,type:str]
sops:
    age:
        - recipient: age1uf70wtw4wad0l7yj39pjzcgzrlh2zg62560zmcq07dk3eg8g49fqkz8rl4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMnQ1bWJzMUJaeSs3Z1dk
            a2JFbXZpMFA5VWJrL2U0ZCtoa2N1NmhWMTJzCkQ3Q3FWSGRoc2pxOXdUM3BEYXMw
            RHRjSzNSMVNUQ09WZDF5YWZYOFg2eUEKLS0tIGpIZU5hQzRINGl1NGtIYXlBam55
            Y2VnQmt4SktqM1JvazVVSmRaaGptUlkKGRc20heWO0ONJbifQhPgwkV/K+1/CNL/
            o2u15A92JGDXOKZlhbviBrsI2Bm5d+IQuto0DW6YSQFQWQkOsUMCBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T04:11:25Z"
    mac: ENC[AES256_GCM,data:wpOnZxE+2O00lPqSBbE6eitknhJzP26ubrYIBxdFTSsicHP+bwbrAxQTW+A/hLE+ak5BKeTuArMWBA1gd78XJDqiQ9qhKyY7TlE5a/Nh+zRVv/nw09/l/iqryaLVggBqEbH/Pte5BbcpVCkaMGmJqlKpQgaFd2t4F/q+56FlBiM=,iv:zzU+UcdrD/EVKbSD+8fKA3YTEpb2qTtLI8d/mMQRFcI=,tag:VrJwM8jrf0wH9+p7u6WVlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
