DATABASE_URL: ENC[AES256_GCM,data:OGA6ePoEHyxYWbryh7Ta7QnSMbPimRv2FbiOL8JvKNuiF1IdXhHzTZaUXbT6Zo0y8q6Qc0lMXFRH01i9qS8HOGyW,iv:4Z3+xSLjUDz9fxBblonqN/O9+uxWDjaOidszbRjBf44=,tag:yKQl+WmbLgSmOE0p8+tqew==,type:str]
REDIS_URL: ENC[AES256_GCM,data:kmMbXAzp+nePa58LURJaKlev5wJGcKDRZw==,iv:w/4IQBCd4QHXjVDnGG3VckldMVzls78Q5bE9YMQkevo=,tag:hjrjZgFbqubykZS+UegyLw==,type:str]
JWT_SECRET: ENC[AES256_GCM,data:IRNYCgOmSY9q09/hjYfuKzktvMmzptfzbBgq1/UxeNK0QA==,iv:X9mdqZd55vzoIV2Z7gA7GMxUJXAmXnZEM22hFczePGs=,tag:U/3qLDQ2Dlu5Eg59J0uqBg==,type:str]
ENV: ENC[AES256_GCM,data:QybiHYOOMrV0bg==,iv:RHFnY8gYcfibOCvK9jJ8ko4tLQTjORAIwgjPX/p81iQ=,tag:WRrAEGFEciagvKGZePw6ZQ==,type:str]
CORS_ORIGINS: ENC[AES256_GCM,data:Gm/+668OWt4Ana7R+NdkINeB7rHYCOGegA==,iv:R03jrhKzz0LDrbtdOmPFQNvpPnjCc12/NhnQdxmcX4k=,tag:bY5MSroxSZrZFj1N3CQ/4Q==,type:str]
WS_ORIGINS: ENC[AES256_GCM,data:DZuTWIylvKVnw+O7HHkZYXUiHBhnO4Q=,iv:h1sRpmDJzwP6S2rQDZ/JQ6WAdagTU8hlFXj24DGncvU=,tag:MIazc1ptek0jrR6YcnTreA==,type:str]
sops:
    age:
        - recipient: age1uf70wtw4wad0l7yj39pjzcgzrlh2zg62560zmcq07dk3eg8g49fqkz8rl4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdDBaci83TVlEbTN3QnYr
            TFRjdXhVdUxOK1N6ck9ZaGgvYklIM2VmakZRCkUrN1JDQkJteDhVZFVhVlhPY1lD
            MXlzNEdDYVp6dG5CUHFzYkxwQ0VPbGsKLS0tIGtCemppdkdXRDRhUmx1Uk45YkJV
            Y2dwN0tFcExxNGttak41cFNGdU10eTQKw+xnA3nBxArU9QBXKuXK1VH8/zN9V7IK
            cGj5PQRou0h/tNb1+m0IEA5gOnnssT3WGy/oHx4BjsWUzH3Di+B8xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T04:15:44Z"
    mac: ENC[AES256_GCM,data:0XM8BkyzBW7qVXo9s+ittgJ7CVcfkHWwNoen0dI/Z1t2nRaABeZNnTNP3NbcLiCvHhByr5bsZ+q4MM99SKowyJljPxieQw4ZIdzU5XB5H1A9BBUXA43ORnwtRF/MSbQO0qMvlvci3LvcBx0O0FcY1x5RZYrfwZCDQOsiETrM/Og=,iv:Xh5omJYYTJ9QvF8el4c6oTzYBLYx/SN4b3VZTAcCYro=,tag:zLNsWVgWtSGLrnnwemeiyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
